In [ ]:
'''Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))'''

In [1]:
import numpy as np

In [5]:
a=np.arange(0,10) #можно ли как-то на место размера поставить N, чтобы N вводилось через input?
a = a[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
'''Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.'''

#Думаю, моя проблема в том, что я не понимаю, как мне вводить N (мой вопрос в первом задании)
#Помогите, пожалуйста, разобраться

In [ ]:
'''Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3'''

In [2]:
from numpy import linalg

a=np.array([[4,2,1],[1,3,0],[0,5,4]])

b=np.array([4,12,-3])

linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [4]:
#Проверка

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [ ]:
'''Задание 4: Имеется матрица покупок в интернет-магазине. 
Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:'''

In [12]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [13]:
#На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [ ]:
'''Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats'''

In [14]:
def cosine(users_stats, next_user_stats):
    
    users_stats_Length = np.linalg.norm(users_stats)
    next_user_stats_Length = np.linalg.norm(next_user_stats)
    
    return np.dot(users_stats, next_user_stats) / (users_stats_Length * next_user_stats_Length)

In [16]:
sim = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)
sim

array([0.2       , 0.84515425, 0.4       , 0.79056942, 0.4       ,
       0.        , 0.        , 0.9486833 , 0.        , 0.        ])

In [22]:
best_sim = np.argmax(sim)

f'Самый похожий к очередному посетителю - пользователь № {best_sim}'

'Самый похожий к очередному посетителю - пользователь № 7'